export const vehicleTypes = ["Van", "Limousine", "Bus", "SUV", "Car", "All"];
export const eventTypes = [
  "Any",
  "Wedding",
  "Birthday",
  "Bachelor Party",
  "Concert",
  "Graduation",
  "Airport",
  "Brewery Tour",
  "Night Club",
  "Brunch",
  "Prom",
  "Corporate",
  "Anniversary",
  "Funeral",
  "Date",
  "Wine Tasting",
  "Bachelorette Party",
];
